plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'az.shlf'
version = '0.0.1-SNAPSHOT'
description = 'telegram-ai-bot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
}

ext {
//    set('springCloudVersion', "2025.1.1")
    set('springAiVersion', "1.1.8")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {
    // Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Database (PostgreSQL + JPA)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'org.postgresql:postgresql'

    // Redis & Kafka
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    // Telegram Bot
    implementation 'org.telegram:telegrambots-spring-boot-starter:6.9.7.1'

    // 5. Documentation (Swagger)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

    // Spring AI (Gemini Chat, Local Transformers Embedding, PgVector)
    implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
    implementation 'org.springframework.ai:spring-ai-starter-model-transformers' // AD YENİLƏNDİ
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector' // AD YENİLƏNDİ

    // feign client
//    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // MinIO
    implementation 'io.minio:minio:8.5.7'

    // Utilities
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

//dependencyManagement {
//    imports {
//        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
//    }
//}

tasks.named('test') {
    useJUnitPlatform()
}