spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29094,localhost:29096}

    consumer:
      group-id: market-data-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "az.shlf.marketdataservice.dto"
        spring.json.value.default.type: az.shlf.marketdataservice.dto.SymbolWatchEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        linger.ms: 5
        batch.size: 16384
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
    admin:
      auto-create: true


app:
  kafka:
    topics:
      hourly-kline:
        name: market-data-hourly-klines
        partitions: 3
        replicas: 3