spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29094,localhost:29096}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        linger.ms: 5
        batch.size: 16384
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000

    consumer:
      group-id: wallet-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "az.shlf.walletservice.listener"
        spring.json.value.default.type: az.shlf.walletservice.listener.dto.WalletCreateEvent

    admin:
      auto-create: true

app:
  kafka:
    topics:
      mail:
        name: mail-topic
        partitions: 3
        replicas: 3
      wallet:
        name: new-user-wallet-topic
        partitions: 3
        replicas: 3
  security:
    mail-token: "mail-sender-token"