spring:
  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:29094,localhost:29096}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


app:
  kafka:
    topics:
      symbol:
        name: symbol-watch-topic
        partitions: 3
        replicas: 3


